import java.util.HashMap;
import java.util.Map;

public class DiccionarioMonedas {
        public static final Map<String, String> currencyMap = new HashMap<>();

        static {
                currencyMap.put("Afganistan", "AFN");
                currencyMap.put("Albania", "ALL");
                currencyMap.put("Argelia", "DZD");
                currencyMap.put("Angola", "AOA");
                currencyMap.put("Armenia", "AMD");
                currencyMap.put("Aruba", "AWG");
                currencyMap.put("Australia", "AUD");
                currencyMap.put("Azerbaiyan", "AZN");
                currencyMap.put("Bahamas", "BSD");
                currencyMap.put("Barein", "BHD");
                currencyMap.put("Banglades", "BDT");
                currencyMap.put("Barbados", "BBD");
                currencyMap.put("Bielorrusia", "BYN");
                currencyMap.put("Belgica", "EUR");
                currencyMap.put("Belice", "BZD");
                currencyMap.put("Benin", "XOF");
                currencyMap.put("Butan", "BTN");
                currencyMap.put("Bolivia", "BOB");
                currencyMap.put("Bosnia y Herzegovina", "BAM");
                currencyMap.put("Botsuana", "BWP");
                currencyMap.put("Brasil", "BRL");
                currencyMap.put("Brunei", "BND");
                currencyMap.put("Bulgaria", "BGN");
                currencyMap.put("Burkina Faso", "XOF");
                currencyMap.put("Burundi", "BIF");
                currencyMap.put("Cabo Verde", "CVE");
                currencyMap.put("Camboya", "KHR");
                currencyMap.put("Camerun", "XAF");
                currencyMap.put("Canada", "CAD");
                currencyMap.put("Republica Centroafricana", "XAF");
                currencyMap.put("Chad", "XAF");
                currencyMap.put("Chile", "CLP");
                currencyMap.put("China", "CNY");
                currencyMap.put("Colombia", "COP");
                currencyMap.put("Comoras", "KMF");
                currencyMap.put("Congo, Republica Democratica del", "CDF");
                currencyMap.put("Congo, Republica del", "XAF");
                currencyMap.put("Costa Rica", "CRC");
                currencyMap.put("Croacia", "HRK");
                currencyMap.put("Cuba", "CUP");
                currencyMap.put("Chipre", "EUR");
                currencyMap.put("Republica Checa", "CZK");
                currencyMap.put("Dinamarca", "DKK");
                currencyMap.put("Yibuti", "DJF");
                currencyMap.put("Dominica", "XCD");
                currencyMap.put("Republica Dominicana", "DOP");
                currencyMap.put("Ecuador", "USD");
                currencyMap.put("Egipto", "EGP");
                currencyMap.put("El Salvador", "USD");
                currencyMap.put("Guinea Ecuatorial", "XAF");
                currencyMap.put("Eritrea", "ERN");
                currencyMap.put("Estonia", "EUR");
                currencyMap.put("Esuatini", "SZL");
                currencyMap.put("Etiopia", "ETB");
                currencyMap.put("Fiyi", "FJD");
                currencyMap.put("Finlandia", "EUR");
                currencyMap.put("Francia", "EUR");
                currencyMap.put("Gabon", "XAF");
                currencyMap.put("Gambia", "GMD");
                currencyMap.put("Georgia", "GEL");
                currencyMap.put("Alemania", "EUR");
                currencyMap.put("Ghana", "GHS");
                currencyMap.put("Grecia", "EUR");
                currencyMap.put("Granada", "XCD");
                currencyMap.put("Guatemala", "GTQ");
                currencyMap.put("Guinea", "GNF");
                currencyMap.put("Guinea-Bisau", "XOF");
                currencyMap.put("Guyana", "GYD");
                currencyMap.put("Haiti", "HTG");
                currencyMap.put("Honduras", "HNL");
                currencyMap.put("Hungria", "HUF");
                currencyMap.put("Islandia", "ISK");
                currencyMap.put("India", "INR");
                currencyMap.put("Indonesia", "IDR");
                currencyMap.put("Iran", "IRR");
                currencyMap.put("Irak", "IQD");
                currencyMap.put("Irlanda", "EUR");
                currencyMap.put("Israel", "ILS");
                currencyMap.put("Italia", "EUR");
                currencyMap.put("Jamaica", "JMD");
                currencyMap.put("Japon", "JPY");
                currencyMap.put("Jordania", "JOD");
                currencyMap.put("Kazajistan", "KZT");
                currencyMap.put("Kenia", "KES");
                currencyMap.put("Kiribati", "KID");
                currencyMap.put("Kuwait", "KWD");
                currencyMap.put("Kirguistan", "KGS");
                currencyMap.put("Laos", "LAK");
                currencyMap.put("Letonia", "EUR");
                currencyMap.put("Libano", "LBP");
                currencyMap.put("Lesoto", "LSL");
                currencyMap.put("Liberia", "LRD");
                currencyMap.put("Libia", "LYD");
                currencyMap.put("Liechtenstein", "CHF");
                currencyMap.put("Lituania", "EUR");
                currencyMap.put("Luxemburgo", "EUR");
                currencyMap.put("Madagascar", "MGA");
                currencyMap.put("Malaui", "MWK");
                currencyMap.put("Malasia", "MYR");
                currencyMap.put("Maldivas", "MVR");
                currencyMap.put("Mali", "XOF");
                currencyMap.put("Malta", "EUR");
                currencyMap.put("Islas Marshall", "USD");
                currencyMap.put("Mauritania", "MRU");
                currencyMap.put("Mauricio", "MUR");
                currencyMap.put("Mexico", "MXN");
                currencyMap.put("Micronesia", "USD");
                currencyMap.put("Moldavia", "MDL");
                currencyMap.put("Monaco", "EUR");
                currencyMap.put("Mongolia", "MNT");
                currencyMap.put("Montenegro", "EUR");
                currencyMap.put("Marruecos", "MAD");
                currencyMap.put("Mozambique", "MZN");
                currencyMap.put("Birmania", "MMK");
                currencyMap.put("Namibia", "NAD");
                currencyMap.put("Nauru", "AUD");
                currencyMap.put("Nepal", "NPR");
                currencyMap.put("Paises Bajos", "EUR");
                currencyMap.put("Nueva Zelanda", "NZD");
                currencyMap.put("Nicaragua", "NIO");
                currencyMap.put("Niger", "XOF");
                currencyMap.put("Nigeria", "NGN");
                currencyMap.put("Macedonia del Norte", "MKD");
                currencyMap.put("Noruega", "NOK");
                currencyMap.put("Oman", "OMR");
                currencyMap.put("Pakistan", "PKR");
                currencyMap.put("Palaos", "USD");
                currencyMap.put("Panama", "PAB");
                currencyMap.put("Papua Nueva Guinea", "PGK");
                currencyMap.put("Paraguay", "PYG");
                currencyMap.put("Peru", "PEN");
                currencyMap.put("Filipinas", "PHP");
                currencyMap.put("Polonia", "PLN");
                currencyMap.put("Portugal", "EUR");
                currencyMap.put("Catar", "QAR");
                currencyMap.put("Rumania", "RON");
                currencyMap.put("Rusia", "RUB");
                currencyMap.put("Ruanda", "RWF");
                currencyMap.put("San Cristobal y Nieves", "XCD");
                currencyMap.put("Santa Lucia", "XCD");
                currencyMap.put("San Vicente y las Granadinas", "XCD");
                currencyMap.put("Samoa", "WST");
                currencyMap.put("San Marino", "EUR");
                currencyMap.put("Santo Tome y Principe", "STN");
                currencyMap.put("Arabia Saudita", "SAR");
                currencyMap.put("Senegal", "XOF");
                currencyMap.put("Serbia", "RSD");
                currencyMap.put("Seychelles", "SCR");
                currencyMap.put("Sierra Leona", "SLE");
                currencyMap.put("Singapur", "SGD");
                currencyMap.put("Eslovaquia", "EUR");
                currencyMap.put("Eslovenia", "EUR");
                currencyMap.put("Islas Salomon", "SBD");
                currencyMap.put("Somalia", "SOS");
                currencyMap.put("Sudafrica", "ZAR");
                currencyMap.put("Corea del Sur", "KRW");
                currencyMap.put("Sudan del Sur", "SSP");
                currencyMap.put("España", "EUR");
                currencyMap.put("Sri Lanka", "LKR");
                currencyMap.put("Sudan", "SDG");
                currencyMap.put("Surinam", "SRD");
                currencyMap.put("Suecia", "SEK");
                currencyMap.put("Suiza", "CHF");
                currencyMap.put("Siria", "SYP");
                currencyMap.put("Taiwan", "TWD");
                currencyMap.put("Tayikistan", "TJS");
                currencyMap.put("Tanzania", "TZS");
                currencyMap.put("Tailandia", "THB");
                currencyMap.put("Timor Oriental", "USD");
                currencyMap.put("Togo", "XOF");
                currencyMap.put("Tonga", "TOP");
                currencyMap.put("Trinidad y Tobago", "TTD");
                currencyMap.put("Tunez", "TND");
                currencyMap.put("Turquia", "TRY");
                currencyMap.put("Turkmenistan", "TMT");
                currencyMap.put("Tuvalu", "TVD");
                currencyMap.put("Uganda", "UGX");
                currencyMap.put("Ucrania", "UAH");
                currencyMap.put("Emiratos Arabes Unidos", "AED");
                currencyMap.put("Reino Unido", "GBP");
                currencyMap.put("Estados Unidos", "USD");
                currencyMap.put("Uruguay", "UYU");
                currencyMap.put("Uzbekistan", "UZS");
                currencyMap.put("Vanuatu", "VUV");
                currencyMap.put("Ciudad del Vaticano", "EUR");
                currencyMap.put("Venezuela", "VES");
                currencyMap.put("Vietnam", "VND");
                currencyMap.put("Yemen", "YER");
                currencyMap.put("Zambia", "ZMW");
                currencyMap.put("Zimbabue", "ZWL");
        }

}
