import java.util.HashMap;
import java.util.Map;

public class DiccinarioMonedas {
    public static final Map<String, String> currencyMap = new HashMap<>();
    static {
            currencyMap.put("Afghanistan", "AFN");
            currencyMap.put("Albania", "ALL");
            currencyMap.put("Algeria", "DZD");
            currencyMap.put("Angola", "AOA");
            currencyMap.put("Armenia", "AMD");
            currencyMap.put("Aruba", "AWG");
            currencyMap.put("Australia", "AUD");
            currencyMap.put("Azerbaijan", "AZN");
            currencyMap.put("Bahamas", "BSD");
            currencyMap.put("Bahrain", "BHD");
            currencyMap.put("Bangladesh", "BDT");
            currencyMap.put("Barbados", "BBD");
            currencyMap.put("Belarus", "BYN");
            currencyMap.put("Belgium", "EUR");
            currencyMap.put("Belize", "BZD");
            currencyMap.put("Benin", "XOF");
            currencyMap.put("Bhutan", "BTN");
            currencyMap.put("Bolivia", "BOB");
            currencyMap.put("Bosnia and Herzegovina", "BAM");
            currencyMap.put("Botswana", "BWP");
            currencyMap.put("Brazil", "BRL");
            currencyMap.put("Brunei", "BND");
            currencyMap.put("Bulgaria", "BGN");
            currencyMap.put("Burkina Faso", "XOF");
            currencyMap.put("Burundi", "BIF");
            currencyMap.put("Cabo Verde", "CVE");
            currencyMap.put("Cambodia", "KHR");
            currencyMap.put("Cameroon", "XAF");
            currencyMap.put("Canada", "CAD");
            currencyMap.put("Central African Republic", "XAF");
            currencyMap.put("Chad", "XAF");
            currencyMap.put("Chile", "CLP");
            currencyMap.put("China", "CNY");
            currencyMap.put("Colombia", "COP");
            currencyMap.put("Comoros", "KMF");
            currencyMap.put("Congo, Democratic Republic of the", "CDF");
            currencyMap.put("Congo, Republic of the", "XAF");
            currencyMap.put("Costa Rica", "CRC");
            currencyMap.put("Croatia", "HRK");
            currencyMap.put("Cuba", "CUP");
            currencyMap.put("Cyprus", "EUR");
            currencyMap.put("Czech Republic", "CZK");
            currencyMap.put("Denmark", "DKK");
            currencyMap.put("Djibouti", "DJF");
            currencyMap.put("Dominica", "XCD");
            currencyMap.put("Dominican Republic", "DOP");
            currencyMap.put("Ecuador", "USD");
            currencyMap.put("Egypt", "EGP");
            currencyMap.put("El Salvador", "USD");
            currencyMap.put("Equatorial Guinea", "XAF");
            currencyMap.put("Eritrea", "ERN");
            currencyMap.put("Estonia", "EUR");
            currencyMap.put("Eswatini", "SZL");
            currencyMap.put("Ethiopia", "ETB");
            currencyMap.put("Fiji", "FJD");
            currencyMap.put("Finland", "EUR");
            currencyMap.put("France", "EUR");
            currencyMap.put("Gabon", "XAF");
            currencyMap.put("Gambia", "GMD");
            currencyMap.put("Georgia", "GEL");
            currencyMap.put("Germany", "EUR");
            currencyMap.put("Ghana", "GHS");
            currencyMap.put("Greece", "EUR");
            currencyMap.put("Grenada", "XCD");
            currencyMap.put("Guatemala", "GTQ");
            currencyMap.put("Guinea", "GNF");
            currencyMap.put("Guinea-Bissau", "XOF");
            currencyMap.put("Guyana", "GYD");
            currencyMap.put("Haiti", "HTG");
            currencyMap.put("Honduras", "HNL");
            currencyMap.put("Hungary", "HUF");
            currencyMap.put("Iceland", "ISK");
            currencyMap.put("India", "INR");
            currencyMap.put("Indonesia", "IDR");
            currencyMap.put("Iran", "IRR");
            currencyMap.put("Iraq", "IQD");
            currencyMap.put("Ireland", "EUR");
            currencyMap.put("Israel", "ILS");
            currencyMap.put("Italy", "EUR");
            currencyMap.put("Jamaica", "JMD");
            currencyMap.put("Japan", "JPY");
            currencyMap.put("Jordan", "JOD");
            currencyMap.put("Kazakhstan", "KZT");
            currencyMap.put("Kenya", "KES");
            currencyMap.put("Kiribati", "KID");
            currencyMap.put("Kuwait", "KWD");
            currencyMap.put("Kyrgyzstan", "KGS");
            currencyMap.put("Laos", "LAK");
            currencyMap.put("Latvia", "EUR");
            currencyMap.put("Lebanon", "LBP");
            currencyMap.put("Lesotho", "LSL");
            currencyMap.put("Liberia", "LRD");
            currencyMap.put("Libya", "LYD");
            currencyMap.put("Liechtenstein", "CHF");
            currencyMap.put("Lithuania", "EUR");
            currencyMap.put("Luxembourg", "EUR");
            currencyMap.put("Madagascar", "MGA");
            currencyMap.put("Malawi", "MWK");
            currencyMap.put("Malaysia", "MYR");
            currencyMap.put("Maldives", "MVR");
            currencyMap.put("Mali", "XOF");
            currencyMap.put("Malta", "EUR");
            currencyMap.put("Marshall Islands", "USD");
            currencyMap.put("Mauritania", "MRU");
            currencyMap.put("Mauritius", "MUR");
            currencyMap.put("Mexico", "MXN");
            currencyMap.put("Micronesia", "USD");
            currencyMap.put("Moldova", "MDL");
            currencyMap.put("Monaco", "EUR");
            currencyMap.put("Mongolia", "MNT");
            currencyMap.put("Montenegro", "EUR");
            currencyMap.put("Morocco", "MAD");
            currencyMap.put("Mozambique", "MZN");
            currencyMap.put("Myanmar", "MMK");
            currencyMap.put("Namibia", "NAD");
            currencyMap.put("Nauru", "AUD");
            currencyMap.put("Nepal", "NPR");
            currencyMap.put("Netherlands", "EUR");
            currencyMap.put("New Zealand", "NZD");
            currencyMap.put("Nicaragua", "NIO");
            currencyMap.put("Niger", "XOF");
            currencyMap.put("Nigeria", "NGN");
            currencyMap.put("North Macedonia", "MKD");
            currencyMap.put("Norway", "NOK");
            currencyMap.put("Oman", "OMR");
            currencyMap.put("Pakistan", "PKR");
            currencyMap.put("Palau", "USD");
            currencyMap.put("Panama", "PAB");
            currencyMap.put("Papua New Guinea", "PGK");
            currencyMap.put("Paraguay", "PYG");
            currencyMap.put("Peru", "PEN");
            currencyMap.put("Philippines", "PHP");
            currencyMap.put("Poland", "PLN");
            currencyMap.put("Portugal", "EUR");
            currencyMap.put("Qatar", "QAR");
            currencyMap.put("Romania", "RON");
            currencyMap.put("Russia", "RUB");
            currencyMap.put("Rwanda", "RWF");
            currencyMap.put("Saint Kitts and Nevis", "XCD");
            currencyMap.put("Saint Lucia", "XCD");
            currencyMap.put("Saint Vincent and the Grenadines", "XCD");
            currencyMap.put("Samoa", "WST");
            currencyMap.put("San Marino", "EUR");
            currencyMap.put("Sao Tome and Principe", "STN");
            currencyMap.put("Saudi Arabia", "SAR");
            currencyMap.put("Senegal", "XOF");
            currencyMap.put("Serbia", "RSD");
            currencyMap.put("Seychelles", "SCR");
            currencyMap.put("Sierra Leone", "SLE");
            currencyMap.put("Singapore", "SGD");
            currencyMap.put("Slovakia", "EUR");
            currencyMap.put("Slovenia", "EUR");
            currencyMap.put("Solomon Islands", "SBD");
            currencyMap.put("Somalia", "SOS");
            currencyMap.put("South Africa", "ZAR");
            currencyMap.put("South Korea", "KRW");
            currencyMap.put("South Sudan", "SSP");
            currencyMap.put("Spain", "EUR");
            currencyMap.put("Sri Lanka", "LKR");
            currencyMap.put("Sudan", "SDG");
            currencyMap.put("Suriname", "SRD");
            currencyMap.put("Sweden", "SEK");
            currencyMap.put("Switzerland", "CHF");
            currencyMap.put("Syria", "SYP");
            currencyMap.put("Taiwan", "TWD");
            currencyMap.put("Tajikistan", "TJS");
            currencyMap.put("Tanzania", "TZS");
            currencyMap.put("Thailand", "THB");
            currencyMap.put("Timor-Leste", "USD");
            currencyMap.put("Togo", "XOF");
            currencyMap.put("Tonga", "TOP");
            currencyMap.put("Trinidad and Tobago", "TTD");
            currencyMap.put("Tunisia", "TND");
            currencyMap.put("Turkey", "TRY");
            currencyMap.put("Turkmenistan", "TMT");
            currencyMap.put("Tuvalu", "TVD");
            currencyMap.put("Uganda", "UGX");
            currencyMap.put("Ukraine", "UAH");
            currencyMap.put("United Arab Emirates", "AED");
            currencyMap.put("United Kingdom", "GBP");
            currencyMap.put("United States", "USD");
            currencyMap.put("Uruguay", "UYU");
            currencyMap.put("Uzbekistan", "UZS");
            currencyMap.put("Vanuatu", "VUV");
            currencyMap.put("Vatican City", "EUR");
            currencyMap.put("Venezuela", "VES");
            currencyMap.put("Vietnam", "VND");
            currencyMap.put("Yemen", "YER");
            currencyMap.put("Zambia", "ZMW");
            currencyMap.put("Zimbabwe", "ZWL");
    }
}
